# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-27 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, verbose_name='Identificador')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name_plural': 'Profissões',
                'ordering': ['nome'],
                'verbose_name': 'Profissão',
            },
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=200, verbose_name='Identigicador')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('fone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('idade', models.CharField(max_length=3, verbose_name='Idade')),
                ('experiencia', models.CharField(max_length=2, verbose_name='Experiência')),
                ('sexo', models.CharField(choices=[('', 'Escolha uma opção'), ('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('profissao', models.ManyToManyField(to='catalogo.Profissao', verbose_name='Profissão')),
            ],
            options={
                'verbose_name_plural': 'Profissionais',
                'ordering': ['nome'],
                'verbose_name': 'Profissional',
            },
        ),
    ]
