# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-13 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='profissionais', verbose_name='Imagem'),
        ),
    ]
